### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by tj** [tj/gobinaries#4]
Sounds like you have to build with musl-gcc: https://www.reddit.com/r/golang/comments/4cxrcv/whats_the_proper_way_to_build_golang_apps_for/

**Comment by ItalyPaleAle** [comment]
Hi @tj I'm having issues with running certain binaries on Alpine, such as this:

```sh
wget -qO - https://gobinaries.com/github.com/markbates/pkger/cmd/pkger@v0.17.1 | sh
```

(Must use wget because curl isn't installed in Alpine by default)

For many packages that don't depend on CGo, it should be sufficient to set `CGO_ENABLED=0` for `go build`. This way, the binaries are 100% static and can run on both platforms with glibc and musl. Of course, this can only be used if the binary itself doesn't use CGo.
